#!/bin/sh
lock() {
    i3lock -i /home/tony/Documents/Desktops/hex.png -c 111111 -d -u
}

case "$1" in
    lock)
        dm-tool lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        dm-tool lock && systemctl suspend
        ;;
    hibernate)
        dm-tool lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
